# Generated by Django 4.1.8 on 2023-05-03 22:15

import cofee.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cofee', '0002_productos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=cofee.models.upload_to),
        ),
    ]
