version: "3.1"

volumes:
  init-data:
  mongo-data:
services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - init-data:/docker-entrypoint-initdb.d
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: cofeedb
    ports:
      - 27017:27017
  web:
    image: app
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    links:
      - mongodb
    volumes:
      - .:/home/cofeetime

    depends_on:
      - migration

  migration:
    build: .
    image: app
    command: python manage.py migrate
    volumes:
      - .:/django_mongodb_docker
    links:
      - mongodb
    depends_on:
      - make_migration
  make_migration:
    build: .
    image: app
    command: python manage.py makemigrations
    volumes:
    - .:/django_mongodb_docker
    links:
      - mongodb
    depends_on:
      - mongodb
  
