version: "3.1"

volumes:
  init-data:
  mongo-data:
services:
  mongodb:
    image: mongo
    restart: always
    volumes:
      - init-data:/docker-entrypoint-initdb.d
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: cofeedb
    ports:
      - 27017:27017

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    image: app_front
    restart: always
    ports:
      - 5174:5173
    volumes:
      - ./client:/home/cofeetime/client
      - /home/cofeetime/client/node_modules
    depends_on:
      - backend
    command: npm run dev
    tty: true
    environment:
      VITE_CONFIG: /home/cofeetime/clien/vite.config.js

  backend:
    build:
      context: ./cafeteria
      dockerfile: Dockerfile.dev
    image: app_back
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    links:
      - mongodb
    volumes:
      - .:/home/cofeetime

    depends_on:
      - migration
  make_migration:
    image: app_back
    command: python manage.py makemigrations
    volumes:
      - .:/django_mongodb_docker
    links:
      - mongodb
    depends_on:
      - mongodb
  migration:
    image: app_back
    command: python manage.py migrate
    volumes:
      - .:/django_mongodb_docker
    links:
      - mongodb
    depends_on:
      - make_migration
