# Generated by Django 4.1.8 on 2023-05-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cofee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
