# Generated by Django 4.1.8 on 2023-05-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cofee', '0004_productos_creator_alter_productos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='descripcion_tiempo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
